yanport/yanport-api-doc

README.md, src/components/parameters/organizationId.yaml, src/components/schemas/ProspectActivity.yaml, src/paths/prospect-activities.yaml
https://github.com/yanport/backlog/issues/903
=> add organizationId to prospect activity model and query

src/components/parameters/GeoSearchQuery-lat.yaml, src/components/parameters/GeoSearchQuery-lng.yaml, src/components/parameters/GeoSearchQuery-radius.yaml, src/components/schemas/GeoSearchQuery.yaml, src/paths/agencies.yaml, src/paths/agglomerations.yaml, src/paths/building-permit.yaml, src/paths/cities.yaml, src/paths/parcels.yaml, src/paths/programs.yaml, src/paths/programs@count.yaml, src/paths/similar-properties.yaml, src/paths/similar-properties@percentiles.yaml
https://github.com/yanport/backlog/issues/971
=>  Précision de nos données géographique

src/openapi.yaml, src/paths/properties@ads@urls.yaml
https://github.com/yanport/yanport-ad/pull/126
=> Trouver un bien à partir d'une url

src/components/parameters/PropertyHistogramQuery-extendedBoundMax.yaml, src/components/parameters/PropertyHistogramQuery-extendedBoundMin.yaml, src/components/parameters/PropertyHistogramQuery-hardBoundMax.yaml, src/components/parameters/PropertyHistogramQuery-hardBoundMin.yaml, src/paths/agencies.yaml, src/paths/agglomerations.yaml, src/paths/api-transactions.yaml, src/paths/api-transactions@evolution@group-by-sku.yaml, src/paths/building-permit.yaml, src/paths/census-stats.yaml, src/paths/cities.yaml, src/paths/iris.yaml, src/paths/mandatary-networks.yaml, src/paths/parcels.yaml, src/paths/programs.yaml, src/paths/properties@distribution.yaml, src/paths/prospect-activities.yaml, src/paths/prospects.yaml, src/paths/quarters.yaml, src/paths/studies.yaml, src/paths/users.yaml
+ changed extendBounMin and extendedBoundMax type
+ fix indentation
=> [histogram query] add hardBounMin and hardBoundMax parameters

src/components/schemas/CommercialZone.yaml, src/components/schemas/Dealer-Type.yaml, src/components/schemas/Module.yaml, src/components/schemas/PersonalInfo.yaml, src/components/schemas/Product.yaml, src/components/schemas/ProductDealer.yaml, src/components/schemas/ProductType.yaml, src/components/schemas/Security.yaml, src/components/schemas/User.yaml, src/paths/users.yaml
https://github.com/yanport/backlog/issues/891
=> Gestion des produits et modules par produit dans Yanport

src/components/schemas/EstimationResponse.yaml, src/paths/properties@estimate.yaml
https://github.com/yanport/backlog/issues/836
=> Interprétabilité des estimations

src/components/parameters/ReliableQuery-reliability.yaml, src/components/schemas/Percentiles.yaml, src/components/schemas/ReliableQueryReliability.yaml, src/components/schemas/Stats.yaml, src/paths/maps.yaml, src/paths/properties@evolution.yaml, src/paths/properties@percentiles.yaml, src/paths/properties@percentiles@group-by-{groupBy}-and-{subGroupBy}.yaml, src/paths/properties@percentiles@group-by-{groupBy}.yaml, src/paths/properties@stats.yaml, src/paths/properties@stats@group-by-{groupBy}-and-{subGroupBy}.yaml, src/paths/properties@stats@group-by-{groupBy}.yaml
https://github.com/yanport/backlog/issues/1122
=> Industrialisation Fiabilité

src/components/parameters/prospectSource.yaml, src/components/schemas/Prospect.yaml, src/paths/prospects.yaml
https://github.com/yanport/backlog/issues/1228
=> Pouvoir suivre la source du lead

src/components/parameters/PropertyHistogramQuery-forecasting.yaml, src/components/schemas/Percentiles.yaml, src/paths/properties@evolution.yaml
https://github.com/yanport/backlog/issues/1195
=> API réponse de nowcasting

src/components/parameters/irisCodes.yaml, src/components/parameters/zone.yaml, src/components/parameters/zoneIds.yaml, src/components/schemas/CensusStats-activity.yaml, src/components/schemas/CensusStats-housing.yaml, src/components/schemas/CensusStats.yaml, src/paths/census-stats.yaml
=> Census-stats: modification du modèle de données

src/components/parameters/PropertyHistogramQuery-forecasting.yaml
https://github.com/yanport/backlog/issues/1471
=> Partir du dernier point fiable pour le forecasting

src/components/parameters/ProgramSearchQuery-stockPreview.yaml, src/components/schemas/ActiveLotCountEvent.yaml, src/components/schemas/Program-Property.yaml, src/components/schemas/Program-Stock.yaml, src/components/schemas/ProgramSearchQuery.yaml, src/paths/programs.yaml, src/paths/programs@count.yaml
https://github.com/yanport/backlog/issues/1403
=> Détecter les queues de lot et les programmes vitrines

src/components/parameters/ProgramSearchQuery-stages.yaml, src/components/schemas/Program-Marketing.yaml, src/components/schemas/ProgramSearchQuery.yaml, src/components/schemas/StageEvent.yaml, src/paths/programs.yaml, src/paths/programs@count.yaml
https://github.com/yanport/backlog/issues/1476
=> Ajouter l'Etat des programmes

src/paths/properties@evolution.yaml, src/paths/properties@evolution@stock.yaml
Typo "constuire" -> construire
=> Fix typo evolution endpoints

src/components/parameters/inseeCodes.yaml, src/components/schemas/Parcel.yaml
https://github.com/yanport/backlog/issues/1553#issue-1616968319
update models : Parcel
=>  Doc API: Mise à jour des modèles

src/components/parameters/anomalyLevelMax.yaml, src/components/parameters/anomalyLevelMin.yaml, src/components/schemas/Anomaly.yaml, src/components/schemas/Cause.yaml, src/components/schemas/Property-Quality.yaml, src/components/schemas/Property.yaml, src/components/schemas/PropertySearchQuery.yaml
https://github.com/yanport/backlog/issues/1604
=> Détection d'anomalies: industrialisation

src/openapi.yaml, src/paths/building-permit@count.yaml, src/paths/building-permit@ids.yaml, src/paths/building-permit@{id}.yaml
https://github.com/yanport/backlog/issues/1558#issue-1617521599
add AD endpoints (building-permit)
=> Doc API: Mise à plat des endpoints

src/paths/properties@evolution@reliable-zone.yaml
https://github.com/yanport/backlog/issues/1735
=> Reliable-zone : intervalUnit fixé côté API

src/components/schemas/Property-Marketing.yaml, src/components/schemas/PropertySearchQuery.yaml
=> Industrialisation tension: Ajout des champs calculés nécessaires (évènements)

src/components/schemas/PropertySearchQuery.yaml
[yanport/backlog#1784](https://github.com/yanport/backlog/issues/1784)
=> Champs DPE/GES doc API

src/paths/properties@{id}.yaml
Refs: https://github.com/yanport/backlog/issues/1963
=> API - Ajouter le verbe HEAD sur properties

src/components/schemas/PersonalInfo.yaml, src/components/schemas/Product.yaml, src/components/schemas/ToggleFeature.yaml, src/components/schemas/ToggleFeatureEvent.yaml, src/components/schemas/User.yaml, src/paths/users.yaml
https://github.com/yanport/backlog/issues/1962
=> Ecrire les cas d'usage IAD via l'API - Refactoring création utilisateur

src/components/schemas/Content-conclusion.yaml, src/components/schemas/Content-estimationEngine.yaml, src/components/schemas/EstimationResponse-reliability.yaml, src/components/schemas/EstimationResponse.yaml
https://github.com/yanport/backlog/issues/2016
=> Dossier V2 - La synthèse des prix

src/components/parameters/DateHistogramQuery-timeZone.yaml, src/paths/api-transactions@evolution@group-by-sku.yaml, src/paths/properties@evolution.yaml
https://github.com/yanport/backlog/issues/1850
=> Module de facturation API - améliorations & correctifs

src/components/parameters/excludedCrawlSources.yaml, src/components/schemas/ProgramSearchQuery.yaml, src/paths/programs.yaml, src/paths/programs@count.yaml
feat: add excluded crawl sources for programs
Refs: https://github.com/yanport/backlog/issues/2077
=> Classements des portails : ajout de excludedCrawlSources pour les programmes

src/paths/properties@evolution@reliable-zone.yaml, src/paths/properties@percentiles@reliable-zone.yaml, src/paths/properties@stats@reliable-zone.yaml
refs: https://github.com/yanport/backlog/issues/2103
=> Reliable-zone: Ajout paramètre furnished

src/components/schemas/AuthenticationMode.yaml, src/components/schemas/Security.yaml
https://github.com/yanport/backlog/issues/1943
=> Différents mode d'authentification : api-doc

src/components/parameters/zone.yaml, src/components/schemas/CensusStats.yaml
Ajouter underscore
Refs: https://github.com/yanport/backlog/issues/2152
=> Census Stats - Market Stress - Type de zone Zip Code

src/components/schemas/ProductType.yaml
https://github.com/yanport/backlog/issues/2130
=> Invest 360 - Ajout du produit dans le BO

src/components/parameters/productTypes.yaml, src/components/schemas/Estimation.yaml, src/components/schemas/Property.yaml, src/components/schemas/PropertySearchQuery.yaml, src/components/schemas/Prospect.yaml, src/components/schemas/ProspectActivity.yaml, src/components/schemas/Study.yaml, src/paths/prospect-activities.yaml, src/paths/prospects.yaml, src/paths/studies.yaml
https://github.com/yanport/backlog/issues/2080
=> Isoler les ressources et modules par produits - Itération 1

src/components/schemas/Content-investmentStats.yaml, src/components/schemas/Content-legal.yaml, src/components/schemas/Content.yaml, src/components/schemas/Marketing-RentControl.yaml, src/components/schemas/Property-Marketing.yaml
https://github.com/yanport/backlog/issues/2160
=> Dossier d'investissement

src/components/schemas/AdRef.yaml, src/components/schemas/Content-investment.yaml, src/components/schemas/Content-pinel.yaml, src/components/schemas/Content.yaml, src/components/schemas/Marketing-Dealer.yaml, src/components/schemas/Opportunity-MarketIndicatorsMethod.yaml, src/components/schemas/Opportunity-ProjectBudget.yaml, src/components/schemas/Opportunity-PropertyFeatures.yaml, src/components/schemas/Opportunity-SimilarPropertiesMethod.yaml, src/components/schemas/Opportunity-UserDefinedMethod.yaml, src/components/schemas/Opportunity-Valuations.yaml, src/components/schemas/Opportunity.yaml, src/components/schemas/PriceEvent.yaml, src/components/schemas/PriceEventRange.yaml, src/components/schemas/Property-Features.yaml, src/components/schemas/Property-Marketing.yaml, src/components/schemas/Property.yaml, src/components/schemas/PropertyRef.yaml, src/components/schemas/RentalExpensesEvent.yaml, src/components/schemas/Study.yaml, src/components/schemas/Summary-renderingMode.yaml, src/components/schemas/Summary-section.yaml, src/components/schemas/Summary-studyPage.yaml
https://github.com/yanport/backlog/issues/2286
=> Invest 360 - Pouvoir saisir mon estimation du bien sur l'opportunité

src/components/schemas/UserSignupForm.yaml, src/openapi.yaml, src/paths/users@signup.yaml
https://github.com/yanport/backlog/issues/2312
=> Documention API pour l'intégration d'avis de valeur dans Dôme de Liberkeys - Ajout de l"inscription utilisateur dans la doc

src/components/schemas/Marketing-Dealer.yaml
https://github.com/yanport/backlog/issues/2288
=> IAD - Prioriser l'affichage des biens vendus par le conseiller dans la liste des biens

src/components/schemas/Features.yaml, src/components/schemas/SimilarProperties.yaml, src/components/schemas/SimilarProperty.yaml, src/components/schemas/Weight.yaml, src/openapi.yaml, src/paths/properties@by-similarity.yaml, src/paths/properties@by-similarity@scoring.yaml, src/paths/properties@percentiles@by-similarity.yaml, src/paths/properties@stats@by-similarity.yaml, src/paths/similar-properties.yaml, src/paths/similar-properties@percentiles.yaml
https://github.com/yanport/backlog/issues/2189
=> Industrialisation biens similaires: modification du service

src/components/schemas/PropertySearchQuery.yaml
Refs: https://github.com/yanport/backlog/issues/2505
=> propertySearchQuery: ajout du champs "dealerPhones"

src/components/schemas/User.yaml
https://github.com/yanport/backlog/issues/2502
=> Ajout de l'external id STRIPE sur l'utilisateur

src/openapi.yaml, src/paths/properties@{id}@by-similarity.yaml, src/paths/properties@{id}@by-similarity@scoring.yaml, src/paths/properties@{id}@percentiles@by-similarity.yaml, src/paths/properties@{id}@stats@by-similarity.yaml
Refs: https://github.com/yanport/backlog/issues/2558
=> fix: params missing and indent

src/components/parameters/DateHistogramQuery-movingFunction.yaml, src/components/parameters/DateHistogramQuery-movingWindow.yaml, src/paths/properties@evolution.yaml
feat: add moving function query params
=> Développement Endpoint evolution - moyennes mobiles

src/components/schemas/Average.yaml, src/components/schemas/CountAgg.yaml, src/components/schemas/DateHistogram.yaml, src/components/schemas/DateHistogramPoint.yaml, src/components/schemas/Growth.yaml, src/components/schemas/Percentiles.yaml, src/components/schemas/PercentilesValues.yaml, src/components/schemas/Reliability.yaml, src/components/schemas/ReliableQueryReliability.yaml, src/components/schemas/Stats.yaml
feat: add growth and reliability models
=> Développement Endpoint evolution - calculs de croissance

src/openapi.yaml, src/paths/maps.yaml, src/paths/maps@properties.yaml
chore: rename maps endpoint to maps properties
=> Maps : renommage endpoint maps

src/components/parameters/PropertyIndicatorQuery-segmentType.yaml, src/components/parameters/PropertyIndicatorQuery-segments.yaml
feat: add construction period segment
=> Indicateurs observatoire: création indicateurs : ajout du segment période de construction

src/components/parameters/PropertyIndicatorQuery-type.yaml
feat: add stock indicators in enum
=> Indicateurs observatoire: indicateurs de volume
